# Generated by Django 3.1.3 on 2020-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0007_auto_20201207_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='purchase_mileage',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
