# Generated by Django 3.1.3 on 2020-12-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0008_car_purchase_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
